openapi: 3.0.3
info:
  title: Ingester
  description: |-
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://ingester.swagger.io/api/v3
tags:
  - name: logs
#   - name: store
#     description: Access to Petstore orders
#     externalDocs:
#       description: Find out more about our store
#       url: http://swagger.io
#   - name: user
#     description: Operations about user
paths:
  /logs:
    post:
      tags:
        - logs
      summary: Receive log lines
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                log: 
                  type: string
      responses:
        '200':
          description: Successful response
        '400':
          description: Invalid input
          headers:
            X-Custom-Header:
              description: Custom header description
              schema:
                type: string
    get:
      tags:
        - logs
      summary: Retrieve logs
      responses:
        '200':
          description: Successful response
        '400':
          description: Invalid input
        
